/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/pc/footer.vue')['default']
    Loadin: typeof import('./src/components/pc/loadin.vue')['default']
    Loading: typeof import('./src/components/pc/loading.vue')['default']
    Phone: typeof import('./src/components/pc/phone.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Top: typeof import('./src/components/pc/top.vue')['default']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
  }
}
